<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NoWarn>1701;1702;CS1591;CS1573,CA2254;RCS1079;CS8618;IDE0022</NoWarn>
		<TargetFrameworks>net5.0;net6.0;net7.0;net8.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>EasyJwt</Title>
		<Authors>helin</Authors>
		<PackageProjectUrl>https://github.com/HeLinSpace/EasyJwt</PackageProjectUrl>
		<RepositoryUrl>https://github.com/HeLinSpace/EasyJwt</RepositoryUrl>
		<IncludeSymbols>True</IncludeSymbols>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>8.0.3.2</Version>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<!-- .NET 5.0 特定包引用 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.30.0" />
	</ItemGroup>

	<!-- .NET 6.0 特定包引用 -->
	<ItemGroup Condition="'$(TargetFramework)' != 'net5.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.0" />
	</ItemGroup>

	<!-- .NET 7.0 特定包引用 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.0" />
	</ItemGroup>

	<!-- .NET 8.0 特定包引用 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
